language: java
env:
  global:
    - secure: "CN/hDQ5CIsJ0+mx99PHYqDjMsdA/w0C+EnyYq2boa3om950hx7VJAyJWm/LJcwty1JL9xcd3QjgoPuswmYZIswRYx9DTwlAnwa5SKlbhiIJN/0/8ZdCYDiAg/FNo86GNb2tkcKfrJLUnbUP8zb6Qb2bR04A4DuLWpv0kqXSN9ATmydeyRwgnBOk6u6Vm6az7beWi96t3dCBKvjSvEUZe7pQTYAjnG4o3kBdKUSL6DtyCNb59O4dD30NoXJvRjsYjjUQTmQW94Vm5SyLDY98L9P5+N1yqInN5PJXWoTB8rId5qdYrEghABx1iA/jCaUQGIBDFu3auokjNAXiG0IEIA3QC5l3NeDo3cWm7/Mtz2H2MCiVNymXcHRVqMinSG5P0++m+NzrPYMW81FK8nTOTFfXYchGlyYufXuBbfxNm2ll8WysdeBq6i1iVPUPTVtJ11rqYPtsBCBqPsaao+5LHq0nJUvDrJ/Z32cVDn6v/TgqE2Tou8YwYe5tKLDGqzrFuj9jqw6LEMYaG0DDuVytT58yXWBQTaHUUXaOdZhwkVs/6VCP+yRSKLngu5jKJK4bvYBUbNq2VVvXBrXDOVpsXEX71gltkEdD+abgofl2SjtrPht5IlNnDPHsiyaDn5SXqQFMFoR0hl92dNlA61Q8SAafDU1uZPSmMMnjhTkOXHRQ="
    - # ^^ OSSRH_JIRA_USERNAME
    - secure: "a8G9vKgaArdpTPTyOmyRPBJAFeGj1yiEdIXg83EcNZjuzPwZ9wnpWeuqraFVktpnb6cIv2JKvazwRXFc1KWBlwNOTDZwNTWlry+jeOHvu6M/goWrLPPnYOeXnHgZvZ4apHUWwsoBoPCrqggqKqP9fqsycS/eGZR/VJXxE8d4VMhXJ0eSIlBryujnGwllisu2b+HrKJr5J/Gk6ezYbnRfetemMjukfPFPg1jwHCEIJ1KnGNYy+hcdeJSclNoeQHNUAtJNuOUB2j/ZyycQUcSi3xO+M44DyQn23pzbjQPuJBn+0hEeg1q4nPp2CL8CLB5ZjcRhfyUhMi1TdzvL3cg+rgBbGkWbsuOV1Znh+Fa5iSWHSmxdnAksr/VCFdooI8k+3blb05DHA+ipXE+gmPMovKLDrP7rbXbchIAIa6XjM4wqC7KsLiiPZcQKsS4lOa6dw35Np0teAb8W6qUqaTKkZfKYCjU0cJQOrnFZce9FUgAiiYqF2SPq7YIk2xJ/7PP5Vbz/0cIzYSIfvoiVUUOn3L5IlSBVQf+o0Hi7UtYXDMm2ZCY2jrnLAsoNbTFHXpYQT5JAVTySa/Ir1fJg7cV3vAv3gMnKu4mhLJ5+oxNccEjW3Fq/+DTkpRvJlo36SNZMA8wVq90pWYOtVHffrsrP2njzAJptMGX+EQhcLInaems="
    - # ^^ OSSRH_JIRA_PASSWORD
    - secure: "jGlsSjgIGb2oQsjFz4CNdAnGY8v5ERzaP79iU4G0Yyy+ypBI5KObuhSA7KMOvgQLXpBFe1Kye7kftKtpH5Ishf3iKlPPu6+TkKuxZW2cGZ5AUZRpvblps0oqDpG9VNJe6cwP0z4zpqjJe2yV9HRaaWw6X+m0W7UxHPH2cltzjmQ2mJ5xwjRUPKIDIwHJeqobYTNLY/iBc9/O+5X90QEiQqbeCwGrKDPzrOIHiVx3LyhAislaIrvnbl0XnRGCrJWmD4aM8kOEIeWyglH4EOFn7Rbs2fUKcu9Zgdquof8soABLKcFoGjwR1rzA4zuudKx5qlAnMxBTQppG6zoB0I6llk7W7rueHWMG3Uu0ubUrO4yQCxqYuCPSMdK8gAHz9CQ6T3eZ+7kYQ/bRTLYFpEpUtum3s93Dyuh/AoKI69V0lDo4lTebVtshHMqPAQlr1XAAvmxDGT8Bd5jU2QMgGpGzPwR7Xz6/2pViDvHlk1uEQnTSk3iS37e8fZAJYKtS4UlLyfyNb2b+bcVnO6z70qxfuKaUXXq1SH1S5vD6YFPIb/L/bqnyDlbgpXuPIbZdVBTIEsD8UZCT5KclPFHrmxXRNDCHWxIybyqT09fr8kPf9BXHGK4hL6+3fSlUYB1QGNSFZGqjuM2zbXEn40YD6kG83n7lg61/zE/Nza7vea5MERQ="
    - # ^^ GPG_PASSPHRASE
    - secure: "KwkDsVZoDMxwCoW1yzMNOoPM0dI/Ow2vEugp/uKNZpEWyTxXr+ZawmiQZSpL0uRy087QJWUPxrKYEmtxaoC0Sksj9sYURjqVGuElOl40JceL2bQrjk2Xa1pnGtGAuMFhuOEU/gRozYk+Wvpt74sCgSSp00y7m2k8CRgfMOdB9/rxbPZm5EfhgGn3/k2dEhkjfo/yEcSX3qBQ1FM9XziKNbX76hNZ3sLT29S9y8zZGOkNHVFIrwbdAUaxf1cPoUfk/sL7jhu+/XVmG2KZs2Uo25M0uZkP5D8QNnG/j4e2Fr3gQt1EJ9Xt0XMQYwXTPXpk+Rb8Y3hFEg7a+UyXuY0AzvGv1nZtUtngg7949gSKK5KLRDP/0MXYBlsQ4DwgLksXFrP7yYyvnwi8Gj4CNdrqOAV45v3elHRmZKiNVnkAZFjZqnNghenQn42uJmOQbQyPq+ceR6JUlQnxTYpb9MyDEP+yD05oxJ8FUeqMY50zcHoVIgv3fDgGGD5jSeHuO21fwNh2xikfjfmoQTSATE/AZhZBDGRTo7fvY1xWmhogMOBu8JU8YlX+NJ0zMs2SrXC1FvefaFc7uIwYZAX5lkBBMsjT4wW4gyUH67rIotCcVh7u7sD/wetZSOnt7wbgLx3Y043tplBQeqG5sCoWNgljkHu73bA58rn/4uUsi6sOd6I="
    - # ^^ GPG_KEY_NAME

before_script:
  - chmod +x ./cd/before-deploy.sh
  - chmod +x ./cd/deploy.sh
  
install: mvn install -P !build-extras -DskipTests=true -Dmaven.javadoc.skip=true -B -V

script: mvn test -P !build-extras -B

cache:
  directories:
    - ~/.m2/repository

after_success:
  - ./cd/before-deploy.sh
  - ./cd/deploy.sh

notifications:
  email:
    recipients:
    - opensource@cs-dev.de
    on_success: change
    on_failure: always
